print("|---------------------------------------------------------|")
Jimmy=input(" What is your brithday\n",)
print("|-----------------------------------------------|")
timmy=input(" What is your brithday\n",)
print("|-----------------------------------------------|")
billy=input(" What is your brithday\n",)
print("|-----------------------------------------------|")
Frank=input(" What is your brithday\n",)
print("|-----------------------------------------------|")
bob=input(" What is your brithday\n",)
print("|--------------------------------------------------------|")

print("Jimmy, this is you brithday: ",Jimmy)
print("|-----------------------------------------------|")
print("Timmy, this is you brithday: ",timmy)
print("|-----------------------------------------------|")
print("Billy, this is you brithday: ",billy)
print("|-----------------------------------------------|")
print("Frank, this is you brithday: ",Frank)
print("|-----------------------------------------------|")
print("Bob, this is you brithday: ",bob)
print("|---------------------------------------------------------|")
